name: clover_app
description: "lotto scripts"
publish_to: 'none'
version: 0.9.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - res/clover_banner.png
    - res/lotto.json